### ISSUE TITLE
The top margin above headings seems excessive in .article?

### ISSUE THREAD

**Issue by michaellenaghan** [fortrabbit/teutonic-css#6]
This is of course subjective, but the top margin [here](https://github.com/fortrabbit/teutonic-css/blob/7887e257aa6734ffde6edaccecb60e30229fdcbd/includes/_article.scss#L62) seems excessive:

```css
  // Spacing on top for headlines!
  h1:not(:first-child)   { margin-top: var(--space-xxl); }
  h2:not(:first-child)   { margin-top: var(--space-xl); }
  h3:not(:first-child)   { margin-top: var(--space-l); }
  h4:not(:first-child)   { margin-top: var(--space-m); }
  h5:not(:first-child)   { margin-top: var(--space-s); }
```

You can see the effect [here](https://teutonic.co/examples/typography#article).
