### ISSUE TITLE
Add .wrap-reverse to .flex?

### ISSUE THREAD

**Issue by michaellenaghan** [fortrabbit/teutonic-css#8]
I'm using flex to create side-by-side columns, with navigation in the left column and content on the right. When the columns collapse I want the navigation to follow rather than precede the content. It turns out that this does what I want:

```css
.flex.wrap-reverse { flex-wrap: wrap-reverse; }
```

(If these suggestions aren't helpful, let me know!)
